# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, unique=True)),
                ('link', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('brand_name',),
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('upd_date', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
            options={
                'ordering': ['last_name', 'first_name', '-add_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('address3', models.CharField(blank=True, max_length=200)),
                ('address4', models.CharField(blank=True, max_length=200)),
                ('postcode', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_type', models.CharField(choices=[('H', 'Home'), ('W', 'Work'), ('M', 'Mobile')], default='H', max_length=1)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_name', models.CharField(max_length=30)),
                ('model', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Brand')),
            ],
            options={
                'ordering': ('brand', 'frame_name', 'model'),
            },
        ),
        migrations.CreateModel(
            name='FramePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Frame')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=30, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='PartSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('placing', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['placing', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('placing', models.PositiveSmallIntegerField()),
                ('includeInSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.PartSection')),
            ],
            options={
                'ordering': ('includeInSection', 'placing', 'shortName'),
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_desc', models.CharField(max_length=30, verbose_name='Quote Description')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('issued_date', models.DateTimeField(blank=True, verbose_name='Date issued')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('frame_cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('frame_sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Customer')),
                ('frame', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Frame')),
            ],
        ),
        migrations.CreateModel(
            name='QuotePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('frame_part', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='epic.FramePart')),
                ('part', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Part')),
                ('partType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.PartType')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Quote')),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='partType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.PartType'),
        ),
        migrations.AddField(
            model_name='framepart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Part'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set([('first_name', 'last_name', 'email')]),
        ),
        migrations.AddField(
            model_name='cell',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Column'),
        ),
        migrations.AddField(
            model_name='cell',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Row'),
        ),
        migrations.AlterUniqueTogether(
            name='quotepart',
            unique_together=set([('quote', 'partType')]),
        ),
        migrations.AlterUniqueTogether(
            name='parttype',
            unique_together=set([('includeInSection', 'shortName')]),
        ),
        migrations.AlterUniqueTogether(
            name='framepart',
            unique_together=set([('frame', 'part')]),
        ),
        migrations.AlterUniqueTogether(
            name='frame',
            unique_together=set([('brand', 'frame_name', 'model')]),
        ),
    ]
