# Generated by Django 2.0.3 on 2019-05-31 09:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('epic', '0001_initial'), ('epic', '0002_auto_20170816_1729'), ('epic', '0003_auto_20170817_1502'), ('epic', '0004_auto_20170817_1715'), ('epic', '0005_auto_20170817_1740'), ('epic', '0006_auto_20170817_1805'), ('epic', '0007_auto_20170817_1809'), ('epic', '0008_auto_20170819_1128'), ('epic', '0009_auto_20170820_0953'), ('epic', '0010_auto_20170828_1216'), ('epic', '0011_auto_20170829_1651'), ('epic', '0012_quote_quote_status'), ('epic', '0013_auto_20170909_1912'), ('epic', '0014_auto_20170909_1926'), ('epic', '0015_auto_20170915_1830'), ('epic', '0016_customernote_customer_visible'), ('epic', '0017_auto_20171001_1207'), ('epic', '0018_orderpayment'), ('epic', '0019_auto_20171021_1720'), ('epic', '0020_auto_20171021_1842'), ('epic', '0021_auto_20171022_2031'), ('epic', '0022_parttypeattribute_default_value_for_quote'), ('epic', '0023_auto_20171029_1216'), ('epic', '0024_auto_20171105_1526'), ('epic', '0025_auto_20171111_1802'), ('epic', '0026_auto_20171119_1504'), ('epic', '0027_brand_supplier'), ('epic', '0028_auto_20171202_1447'), ('epic', '0029_remove_quotepart_not_applicable'), ('epic', '0030_auto_20171210_1134'), ('epic', '0031_auto_20171227_1452'), ('epic', '0032_auto_20180127_0929'), ('epic', '0033_auto_20180225_1029'), ('epic', '0034_auto_20180310_1220'), ('epic', '0035_auto_20180317_1919'), ('epic', '0036_frame_sizes'), ('epic', '0037_auto_20180324_1219'), ('epic', '0038_auto_20180331_1359'), ('epic', '0039_remove_quote_frame_cost_price'), ('epic', '0040_auto_20180412_1857'), ('epic', '0041_auto_20180415_1417'), ('epic', '0042_auto_20180429_1803'), ('epic', '0043_auto_20180527_1244'), ('epic', '0044_auto_20180527_1738'), ('epic', '0045_auto_20180602_1258'), ('epic', '0046_auto_20180608_1205'), ('epic', '0047_auto_20180621_0945'), ('epic', '0048_auto_20180622_1959'), ('epic', '0049_auto_20180629_1200'), ('epic', '0050_auto_20181103_1835'), ('epic', '0051_auto_20181124_1754'), ('epic', '0052_auto_20181125_1146'), ('epic', '0053_auto_20181201_1702'), ('epic', '0054_auto_20181214_1927'), ('epic', '0055_auto_20181223_1227'), ('epic', '0056_auto_20181228_1657'), ('epic', '0057_supplierproduct_check_date'), ('epic', '0058_auto_20190112_1410'), ('epic', '0059_auto_20190117_1856'), ('epic', '0060_remove_quote_quote_type'), ('epic', '0061_auto_20190119_1113'), ('epic', '0062_auto_20190322_1402'), ('epic', '0063_auto_20190404_1103'), ('epic', '0064_auto_20190405_1547'), ('epic', '0065_auto_20190408_1751'), ('epic', '0066_auto_20190410_0953'), ('epic', '0067_auto_20190413_2116'), ('epic', '0068_quote_club_member'), ('epic', '0069_auto_20190416_1336'), ('epic', '0070_auto_20190425_1612'), ('epic', '0071_quote_bike_price'), ('epic', '0072_customer_club_member')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, unique=True)),
                ('link', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('brand_name',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('upd_date', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
            options={
                'ordering': ['last_name', 'first_name', '-add_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('address3', models.CharField(blank=True, max_length=200)),
                ('address4', models.CharField(blank=True, max_length=200)),
                ('postcode', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Customer')),
                ('upd_date', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_type', models.CharField(choices=[('H', 'Home'), ('W', 'Work'), ('M', 'Mobile')], default='H', max_length=1)),
                ('telephone', models.CharField(blank=True, max_length=60)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Customer')),
                ('upd_date', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_name', models.CharField(max_length=30)),
                ('model', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Brand')),
            ],
            options={
                'ordering': ('brand', 'frame_name', 'model'),
            },
        ),
        migrations.CreateModel(
            name='FramePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Frame')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=30, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='PartSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('placing', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['placing', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('placing', models.PositiveSmallIntegerField()),
                ('includeInSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.PartSection')),
            ],
            options={
                'ordering': ('includeInSection', 'placing', 'shortName'),
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_desc', models.CharField(max_length=30, verbose_name='Quote Description')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('issued_date', models.DateTimeField(blank=True, verbose_name='Date issued')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('frame_cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('frame_sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Customer')),
                ('frame', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Frame')),
            ],
        ),
        migrations.CreateModel(
            name='QuotePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('frame_part', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='epic.FramePart')),
                ('part', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Part')),
                ('partType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.PartType')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Quote')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='partType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.PartType'),
        ),
        migrations.AddField(
            model_name='framepart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Part'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('first_name', 'last_name', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='quotepart',
            unique_together={('quote', 'partType')},
        ),
        migrations.AlterUniqueTogether(
            name='parttype',
            unique_together={('includeInSection', 'shortName')},
        ),
        migrations.AlterUniqueTogether(
            name='framepart',
            unique_together={('frame', 'part')},
        ),
        migrations.AlterUniqueTogether(
            name='frame',
            unique_together={('brand', 'frame_name', 'model')},
        ),
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('partType', 'brand', 'part_name')},
        ),
        migrations.CreateModel(
            name='Fitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitting_type', models.CharField(choices=[('C', 'Customer'), ('E', 'Epic')], default='E', max_length=1, verbose_name='Type')),
                ('saddle_height', models.CharField(max_length=20, verbose_name='Saddle Height')),
                ('bar_height', models.CharField(max_length=20, verbose_name='Bar Height')),
                ('reach', models.CharField(max_length=20, verbose_name='Reach')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='frame',
            name='frame_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='frame',
            name='model',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='partsection',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='shortName',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_desc',
            field=models.CharField(max_length=60, verbose_name='Quote Description'),
        ),
        migrations.AddField(
            model_name='fitting',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Customer'),
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ('-created_date', 'quote_desc')},
        ),
        migrations.AddField(
            model_name='quote',
            name='fitting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Fitting'),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_type',
            field=models.CharField(choices=[('B', 'Bike'), ('P', 'Parts')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='quote',
            name='version',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='issued_date',
            field=models.DateTimeField(null=True, verbose_name='Date issued'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.RemoveField(
            model_name='quote',
            name='frame_cost_price',
        ),
        migrations.AlterField(
            model_name='quote',
            name='frame_sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Frame'),
        ),
        migrations.AlterModelOptions(
            name='quotepart',
            options={'ordering': ('line', '-quote')},
        ),
        migrations.AddField(
            model_name='quotepart',
            name='line',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quotepart',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='quotepart',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='quotepart',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='quotepart',
            name='frame_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.FramePart'),
        ),
        migrations.AlterField(
            model_name='quotepart',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Part'),
        ),
        migrations.AlterModelOptions(
            name='quotepart',
            options={'ordering': ('line', '-quote')},
        ),
        migrations.AddField(
            model_name='quote',
            name='keyed_sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='quotepart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_status',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Issued'), ('3', 'Archived'), ('4', 'Order Created')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('completed_date', models.DateTimeField(null=True, verbose_name='Date complete')),
                ('customer_required_date', models.DateField(null=True, verbose_name='Customer Date')),
                ('final_date', models.DateField(null=True, verbose_name='Handover Date')),
                ('order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadtime', models.IntegerField(blank=True, null=True, verbose_name='Leadtime (weeks)')),
                ('receipt_date', models.DateTimeField(null=True, verbose_name='Date received')),
                ('customerOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.CustomerOrder')),
                ('frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Frame')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadtime', models.IntegerField(blank=True, null=True, verbose_name='Leadtime (weeks)')),
                ('receipt_date', models.DateTimeField(null=True, verbose_name='Date received')),
                ('customerOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.CustomerOrder')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Part')),
            ],
        ),
        migrations.CreateModel(
            name='PartTypeAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=30, unique=True)),
                ('in_use', models.BooleanField()),
                ('mandatory', models.BooleanField()),
                ('placing', models.PositiveSmallIntegerField()),
                ('partType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.PartType')),
            ],
            options={
                'ordering': ('placing',),
            },
        ),
        migrations.CreateModel(
            name='QuotePartAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.CharField(max_length=40, null=True)),
                ('partTypeAttribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.PartTypeAttribute')),
                ('quotePart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.QuotePart')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100, unique=True, verbose_name='Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_identifier', models.CharField(max_length=20, unique=True, verbose_name='Order')),
                ('date_placed', models.DateField(null=True, verbose_name='Order Date')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField(verbose_name='Detail')),
                ('supplierOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.SupplierOrder')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='epic.Supplier'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='supplierOrderItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.SupplierOrderItem'),
        ),
        migrations.AddField(
            model_name='orderframe',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Supplier'),
        ),
        migrations.AddField(
            model_name='orderframe',
            name='supplierOrderItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.SupplierOrderItem'),
        ),
        migrations.AddField(
            model_name='customernote',
            name='customerOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.CustomerOrder'),
        ),
        migrations.AddField(
            model_name='customernote',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Quote'),
        ),
        migrations.AddField(
            model_name='quote',
            name='customerOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.CustomerOrder'),
        ),
        migrations.AlterUniqueTogether(
            name='parttypeattribute',
            unique_together={('partType', 'attribute_name')},
        ),
        migrations.AlterField(
            model_name='parttypeattribute',
            name='attribute_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='customernote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customernote',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='quotepartattribute',
            unique_together={('quotePart', 'partTypeAttribute')},
        ),
        migrations.AddField(
            model_name='customernote',
            name='customer_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='cancelled_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderframe',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Quote'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quotePart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.QuotePart'),
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Payment Amount')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date complete'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='customer_required_date',
            field=models.DateField(blank=True, null=True, verbose_name='Customer Date'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='final_date',
            field=models.DateField(blank=True, null=True, verbose_name='Handover Date'),
        ),
        migrations.AlterField(
            model_name='orderframe',
            name='receipt_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date received'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='receipt_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date received'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='date_placed',
            field=models.DateField(blank=True, null=True, verbose_name='Order Date'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='customerOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.CustomerOrder'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='order_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='parttype',
            name='can_be_omitted',
            field=models.BooleanField(default=False, verbose_name='Can be omitted'),
        ),
        migrations.AddField(
            model_name='parttype',
            name='can_be_substituted',
            field=models.BooleanField(default=False, verbose_name='Can be substituted'),
        ),
        migrations.AddField(
            model_name='frame',
            name='colour',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='frame',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='parttype',
            name='customer_facing',
            field=models.BooleanField(default=False, verbose_name='Show Customer'),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='trade_in_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='quotepart',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='quotepart',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='date_placed',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Order Date'),
        ),
        migrations.AddField(
            model_name='quote',
            name='colour',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='colour_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='frame_size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Supplier'),
        ),
        migrations.CreateModel(
            name='FrameExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Frame')),
                ('partType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.PartType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='frameexclusion',
            unique_together={('frame', 'partType')},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stock_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='order_identifier',
            field=models.CharField(max_length=20, verbose_name='Order'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierorder',
            unique_together={('supplier', 'order_identifier')},
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='customer_required_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='final_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='issued_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_desc',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='AttributeOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_option', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='customerorder',
            options={'ordering': ('-created_date', 'customer')},
        ),
        migrations.AddField(
            model_name='parttypeattribute',
            name='attribute_type',
            field=models.CharField(choices=[('1', 'Text'), ('2', 'Numeric'), ('3', 'Single - Radio'), ('4', 'Single - Dropdown'), ('5', 'Multiple - Checkbox'), ('6', 'Multiple - Dropdown')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='attributeoptions',
            name='part_type_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.PartTypeAttribute'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='colour',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='frame',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frame',
            name='sizes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterModelOptions(
            name='framepart',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='is_incomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='is_not_standard_part',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='can_be_issued',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='can_be_ordered',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelOptions(
            name='quotepart',
            options={},
        ),
        migrations.RenameField(
            model_name='quotepart',
            old_name='is_not_standard_part',
            new_name='replacement_part',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='frame_part',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='line',
        ),
        migrations.AddField(
            model_name='fitting',
            name='upd_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name', 'last_name', 'email'], name='epic_custom_first_n_8b4ffd_idx'),
        ),
        migrations.AlterField(
            model_name='quotepart',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterModelOptions(
            name='attributeoptions',
            options={'ordering': ('attribute_option',)},
        ),
        migrations.AlterField(
            model_name='brand',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerphone',
            name='telephone',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='parttypeattribute',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parttypeattribute',
            name='mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='frame',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='frameexclusion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='framepart',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='parttype',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='parttypeattribute',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='quotepartattribute',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supplierorder',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='attributeoptions',
            index=models.Index(fields=['part_type_attribute', 'attribute_option'], name='epic_attrib_part_ty_8d8194_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['brand_name'], name='epic_brand_brand_n_646d32_idx'),
        ),
        migrations.AddIndex(
            model_name='frame',
            index=models.Index(fields=['brand', 'frame_name', 'model'], name='epic_frame_brand_i_687d95_idx'),
        ),
        migrations.AddIndex(
            model_name='frameexclusion',
            index=models.Index(fields=['frame', 'partType'], name='epic_framee_frame_i_bf7a83_idx'),
        ),
        migrations.AddIndex(
            model_name='framepart',
            index=models.Index(fields=['frame', 'part'], name='epic_framep_frame_i_ae502a_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['partType', 'brand', 'part_name'], name='epic_part_partTyp_15352f_idx'),
        ),
        migrations.AddIndex(
            model_name='parttype',
            index=models.Index(fields=['includeInSection', 'shortName'], name='epic_partty_include_5e850d_idx'),
        ),
        migrations.AddIndex(
            model_name='parttypeattribute',
            index=models.Index(fields=['partType', 'attribute_name'], name='epic_partty_partTyp_87fce1_idx'),
        ),
        migrations.AddIndex(
            model_name='quotepartattribute',
            index=models.Index(fields=['quotePart', 'partTypeAttribute'], name='epic_quotep_quotePa_9c8c60_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierorder',
            index=models.Index(fields=['supplier', 'order_identifier'], name='epic_suppli_supplie_39c7b1_idx'),
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderframe',
            name='customerOrder',
        ),
        migrations.RemoveField(
            model_name='orderframe',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='orderframe',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='orderframe',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='orderframe',
            name='supplierOrderItem',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='customerOrder',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='part',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quotePart',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='supplierOrderItem',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='customerOrder',
        ),
        migrations.RemoveField(
            model_name='supplierorder',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplierorderitem',
            name='supplierOrder',
        ),
        migrations.RemoveField(
            model_name='customernote',
            name='customerOrder',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='can_be_ordered',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='customerOrder',
        ),
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
        migrations.DeleteModel(
            name='OrderFrame',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='OrderPayment',
        ),
        migrations.DeleteModel(
            name='SupplierOrder',
        ),
        migrations.DeleteModel(
            name='SupplierOrderItem',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='cost_price',
        ),
        migrations.AddField(
            model_name='quote',
            name='upd_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='colour',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='model',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='frame',
            name='sizes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frame',
            name='archived_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='parttype',
            name='description',
        ),
        migrations.AddField(
            model_name='attributeoptions',
            name='placing',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attributeoptions',
            name='part_type_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='epic.PartTypeAttribute'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='epic.Customer'),
        ),
        migrations.AlterField(
            model_name='customernote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customernote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='epic.Customer'),
        ),
        migrations.AlterField(
            model_name='customernote',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='epic.Quote'),
        ),
        migrations.AlterField(
            model_name='customerphone',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='epic.Customer'),
        ),
        migrations.AlterField(
            model_name='fitting',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fittings', to='epic.Customer'),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='includeInSection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partTypes', to='epic.PartSection'),
        ),
        migrations.AlterField(
            model_name='parttypeattribute',
            name='partType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='epic.PartType'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='epic.Customer'),
        ),
        migrations.AlterModelOptions(
            name='attributeoptions',
            options={'ordering': ('placing',)},
        ),
        migrations.RemoveField(
            model_name='brand',
            name='supplier',
        ),
        migrations.AddField(
            model_name='brand',
            name='supplier',
            field=models.ManyToManyField(blank=True, to='epic.Supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='preferred_supplier',
            field=models.BooleanField(default=True, verbose_name='Preferred'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.CharField(blank=True, max_length=200, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('colours', models.CharField(blank=True, max_length=400, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('sizes', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BikePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_name', models.CharField(max_length=100, unique=True, verbose_name='Supplier')),
                ('fitted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartTradeIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_in_value', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartTypeSynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=30)),
                ('fitted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('rrp', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('trade_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('club_discount', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='framepart',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='framepart',
            name='part',
        ),
        migrations.AlterModelOptions(
            name='frame',
            options={'ordering': ('brand', 'frame_name')},
        ),
        migrations.RemoveIndex(
            model_name='frame',
            name='epic_frame_brand_i_687d95_idx',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='description',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='model',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='sizes',
        ),
        migrations.AddField(
            model_name='part',
            name='stocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='frame',
            index=models.Index(fields=['brand', 'frame_name'], name='epic_frame_brand_i_fae71e_idx'),
        ),
        migrations.DeleteModel(
            name='FramePart',
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Part'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Supplier'),
        ),
        migrations.AddField(
            model_name='parttypesynonym',
            name='partType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='epic.PartType'),
        ),
        migrations.AddField(
            model_name='parttradein',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Part'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='products',
            field=models.ManyToManyField(blank=True, to='epic.SupplierProduct'),
        ),
        migrations.AddField(
            model_name='bikepart',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Bike'),
        ),
        migrations.AddField(
            model_name='bikepart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Part'),
        ),
        migrations.AddField(
            model_name='bike',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Frame'),
        ),
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['supplier', 'part'], name='epic_suppli_supplie_040de4_idx'),
        ),
        migrations.AddIndex(
            model_name='bikepart',
            index=models.Index(fields=['bike', 'part'], name='epic_bikepa_bike_id_03189d_idx'),
        ),
        migrations.RemoveField(
            model_name='parttradein',
            name='part',
        ),
        migrations.AddField(
            model_name='brand',
            name='bike_brand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='standard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='trade_in_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='epic.Frame'),
        ),
        migrations.DeleteModel(
            name='PartTradeIn',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='frame',
        ),
        migrations.AddField(
            model_name='quote',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Bike'),
        ),
        migrations.RenameField(
            model_name='bike',
            old_name='sell_price',
            new_name='club_price',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='club_discount',
        ),
        migrations.AddField(
            model_name='bike',
            name='epic_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='rrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='club_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='bundle_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='check_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='country',
            field=models.CharField(default='GB', max_length=2),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterModelOptions(
            name='parttype',
            options={'ordering': ('includeInSection', 'placing', 'name')},
        ),
        migrations.RemoveIndex(
            model_name='attributeoptions',
            name='epic_attrib_part_ty_8d8194_idx',
        ),
        migrations.RemoveIndex(
            model_name='parttype',
            name='epic_partty_include_5e850d_idx',
        ),
        migrations.RenameField(
            model_name='attributeoptions',
            old_name='attribute_option',
            new_name='option_name',
        ),
        migrations.RenameField(
            model_name='customernote',
            old_name='created_on',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='fitting',
            old_name='notes',
            new_name='note_text',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='trade_in_value',
            new_name='trade_in_price',
        ),
        migrations.RenameField(
            model_name='parttype',
            old_name='customer_facing',
            new_name='customer_visible',
        ),
        migrations.RenameField(
            model_name='parttype',
            old_name='shortName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='parttypesynonym',
            old_name='shortName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='frame_sell_price',
            new_name='bike_price',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='keyed_sell_price',
            new_name='epic_price',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='sell_price',
            new_name='rrp',
        ),
        migrations.RenameField(
            model_name='quotepart',
            old_name='sell_price',
            new_name='epic_price',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='website',
            new_name='link',
        ),
        migrations.AddField(
            model_name='quotepart',
            name='rrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddIndex(
            model_name='attributeoptions',
            index=models.Index(fields=['part_type_attribute', 'option_name'], name='epic_attrib_part_ty_0587db_idx'),
        ),
        migrations.AddIndex(
            model_name='parttype',
            index=models.Index(fields=['includeInSection', 'name'], name='epic_partty_include_8d9d73_idx'),
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quote_type',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='bike_price',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='part_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.RemoveField(
            model_name='quote',
            name='can_be_issued',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='is_incomplete',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerphone',
            name='preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bike',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Frame'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_desc',
            field=models.CharField(max_length=120),
        ),
        migrations.RemoveField(
            model_name='quote',
            name='epic_price',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='rrp',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='epic_price',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='rrp',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='trade_in_price',
        ),
        migrations.RemoveField(
            model_name='quotepartattribute',
            name='partTypeAttribute',
        ),
        migrations.RemoveField(
            model_name='quotepartattribute',
            name='quotePart',
        ),
        migrations.AddField(
            model_name='quotepart',
            name='additional_data',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='QuotePartAttribute',
        ),
        migrations.RenameField(
            model_name='quotepart',
            old_name='replacement_part',
            new_name='not_required',
        ),
        migrations.AddField(
            model_name='quotepart',
            name='trade_in_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Supplier'),
        ),
        migrations.AddField(
            model_name='quote',
            name='club_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='club_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterModelOptions(
            name='customernote',
            options={'ordering': ('-created_date', 'created_by')},
        ),
        migrations.AddField(
            model_name='quote',
            name='calculated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='bike_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='club_member',
            field=models.BooleanField(default=False),
        ),
    ]
