# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('upd_date', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('address3', models.CharField(blank=True, max_length=200)),
                ('address4', models.CharField(blank=True, max_length=200)),
                ('postcode', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_type', models.CharField(choices=[('H', 'Home'), ('W', 'Work'), ('M', 'Mobile')], default='H', max_length=1)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='FramePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Frame')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='framepart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Part'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set([('first_name', 'last_name', 'email')]),
        ),
        migrations.AlterUniqueTogether(
            name='framepart',
            unique_together=set([('frame', 'part')]),
        ),
        migrations.AlterUniqueTogether(
            name='frame',
            unique_together=set([('brand', 'shortName')]),
        ),
    ]
