# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-14 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PartSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('placing', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['placing', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('placing', models.PositiveSmallIntegerField()),
                ('includeInSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.PartSection')),
            ],
            options={
                'ordering': ('includeInSection', 'placing', 'shortName'),
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('issued_date', models.DateTimeField(blank=True, verbose_name='Date issued')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('frame_cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('frame_sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='QuotePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name', 'first_name', '-add_date']},
        ),
        migrations.AlterModelOptions(
            name='frame',
            options={'ordering': ('brand', 'name', 'model')},
        ),
        migrations.RenameField(
            model_name='part',
            old_name='shortName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='framepart',
            name='description',
        ),
        migrations.RemoveField(
            model_name='part',
            name='description',
        ),
        migrations.AddField(
            model_name='frame',
            name='model',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='frame',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='brand',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='epic.Brand'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='frame',
            name='shortName',
        ),
        migrations.AlterUniqueTogether(
            name='frame',
            unique_together=set([('brand', 'name', 'model')]),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='frame_part',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='epic.FramePart'),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='part',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Part'),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='partType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.PartType'),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Quote'),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Customer'),
        ),
        migrations.AddField(
            model_name='quote',
            name='frame',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Frame'),
        ),
        migrations.AddField(
            model_name='cell',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Column'),
        ),
        migrations.AddField(
            model_name='cell',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Row'),
        ),
        migrations.AddField(
            model_name='part',
            name='partType',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='epic.PartType'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='quotepart',
            unique_together=set([('quote', 'partType')]),
        ),
        migrations.AlterUniqueTogether(
            name='parttype',
            unique_together=set([('includeInSection', 'shortName')]),
        ),
    ]
