# Generated by Django 2.0.3 on 2019-06-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0001_squashed_0072_customer_club_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='product_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
