# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together=set([('partType', 'brand', 'part_name')]),
        ),
    ]
