# Generated by Django 2.0.3 on 2019-07-14 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epic', '0002_auto_20190620_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='products',
        ),
        migrations.AddField(
            model_name='bike',
            name='product_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='rrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='upd_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='part',
            name='upd_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='upd_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Bundle',
        ),
    ]
