# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0002_auto_20170814_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
