# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0002_auto_20170816_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitting_type', models.CharField(choices=[('C', 'Customer'), ('E', 'Epic')], default='E', max_length=1, verbose_name='Type')),
                ('saddle_height', models.CharField(max_length=20, verbose_name='Saddle Height')),
                ('bar_height', models.CharField(max_length=20, verbose_name='Bar Height')),
                ('reach', models.CharField(max_length=20, verbose_name='Reach')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='customerphone',
            name='telephone',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='frame',
            name='frame_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='frame',
            name='model',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='partsection',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='shortName',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_desc',
            field=models.CharField(max_length=60, verbose_name='Quote Description'),
        ),
        migrations.AddField(
            model_name='fitting',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Customer'),
        ),
    ]
