# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0003_auto_20170817_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ('-created_date', 'quote_desc')},
        ),
        migrations.AddField(
            model_name='quote',
            name='fitting',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='epic.Fitting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_type',
            field=models.CharField(choices=[('B', 'Bike'), ('P', 'Parts')], default='B', max_length=1, verbose_name='Type'),
        ),
    ]
