# Generated by Django 2.0.3 on 2019-07-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0003_auto_20190714_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotepart',
            name='club_price',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='ticket_price',
        ),
    ]
