# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0004_auto_20170817_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='version',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='issued_date',
            field=models.DateTimeField(null=True, verbose_name='Date issued'),
        ),
    ]
