# Generated by Django 2.0.3 on 2019-08-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0006_auto_20190801_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='supplier',
            field=models.ManyToManyField(blank=True, to='epic.Supplier'),
        ),
    ]
