# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-19 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0007_auto_20170817_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotepart',
            options={'ordering': ('line', '-quote')},
        ),
        migrations.AddField(
            model_name='quotepart',
            name='line',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quotepart',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='quotepart',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='quotepart',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
