# Generated by Django 2.0.3 on 2019-08-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0007_auto_20190802_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='colour_price',
        ),
        migrations.AddField(
            model_name='customernote',
            name='system_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='fixed_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
