# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-20 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0008_auto_20170819_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotepart',
            name='frame_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.FramePart'),
        ),
        migrations.AlterField(
            model_name='quotepart',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Part'),
        ),
    ]
