# Generated by Django 2.0.3 on 2019-08-25 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epic', '0008_auto_20190816_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('upd_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Question')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Quote')),
            ],
        ),
        migrations.AddField(
            model_name='charge',
            name='can_be_zero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charge',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Charge'),
        ),
        migrations.AddField(
            model_name='question',
            name='upd_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
