# Generated by Django 2.0.3 on 2019-08-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0009_auto_20190825_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bike_only',
            field=models.BooleanField(default=False),
        ),
    ]
