# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0009_auto_20170820_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotepart',
            options={},
        ),
        migrations.AddField(
            model_name='quote',
            name='keyed_sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
