# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0010_auto_20170828_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotepart',
            options={'ordering': ('line', '-quote')},
        ),
        migrations.AlterUniqueTogether(
            name='quotepart',
            unique_together=set([]),
        ),
    ]
