# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-09 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0011_auto_20170829_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_status',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Quoted'), ('3', 'Archived'), ('4', 'Order Created')], default='1', max_length=1, verbose_name='Status'),
        ),
    ]
