# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-09 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0012_quote_quote_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('completed_date', models.DateTimeField(null=True, verbose_name='Date complete')),
                ('customer_required_date', models.DateField(null=True, verbose_name='Customer Date')),
                ('final_date', models.DateField(null=True, verbose_name='Handover Date')),
                ('order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadtime', models.IntegerField(blank=True, null=True, verbose_name='Leadtime (weeks)')),
                ('receipt_date', models.DateTimeField(null=True, verbose_name='Date received')),
                ('customerOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.CustomerOrder')),
                ('frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Frame')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadtime', models.IntegerField(blank=True, null=True, verbose_name='Leadtime (weeks)')),
                ('receipt_date', models.DateTimeField(null=True, verbose_name='Date received')),
                ('customerOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.CustomerOrder')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Part')),
            ],
        ),
        migrations.CreateModel(
            name='PartTypeAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=30, unique=True)),
                ('in_use', models.BooleanField()),
                ('mandatory', models.BooleanField()),
                ('placing', models.PositiveSmallIntegerField()),
                ('partType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.PartType')),
            ],
            options={
                'ordering': ('placing',),
            },
        ),
        migrations.CreateModel(
            name='QuotePartAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.CharField(max_length=40, verbose_name='Quote Description')),
                ('partTypeAttribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.PartTypeAttribute')),
                ('quotePart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.QuotePart')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100, unique=True, verbose_name='Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_identifier', models.CharField(max_length=20, unique=True, verbose_name='Order')),
                ('date_placed', models.DateField(null=True, verbose_name='Order Date')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField(verbose_name='Detail')),
                ('supplierOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.SupplierOrder')),
            ],
        ),
        migrations.RemoveField(
            model_name='cell',
            name='column',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='row',
        ),
        migrations.DeleteModel(
            name='Cell',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='Row',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Supplier'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='supplierOrderItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.SupplierOrderItem'),
        ),
        migrations.AddField(
            model_name='orderframe',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Supplier'),
        ),
        migrations.AddField(
            model_name='orderframe',
            name='supplierOrderItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.SupplierOrderItem'),
        ),
        migrations.AddField(
            model_name='customernote',
            name='customerOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.CustomerOrder'),
        ),
        migrations.AddField(
            model_name='customernote',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Quote'),
        ),
        migrations.AddField(
            model_name='quote',
            name='customerOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.CustomerOrder'),
        ),
        migrations.AlterUniqueTogether(
            name='parttypeattribute',
            unique_together=set([('partType', 'attribute_name')]),
        ),
    ]
