# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-09 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0013_auto_20170909_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttypeattribute',
            name='attribute_name',
            field=models.CharField(max_length=30),
        ),
    ]
