# Generated by Django 2.2.8 on 2020-02-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0013_auto_20200122_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frameexclusion',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='frameexclusion',
            name='partType',
        ),
        migrations.AddField(
            model_name='bike',
            name='bikeParts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BikePart',
        ),
        migrations.DeleteModel(
            name='FrameExclusion',
        ),
    ]
