# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-01 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0016_customernote_customer_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='cancelled_date',
            field=models.DateTimeField(null=True, verbose_name='Date cancelled'),
        ),
        migrations.AddField(
            model_name='historicalcustomerorder',
            name='cancelled_date',
            field=models.DateTimeField(null=True, verbose_name='Date cancelled'),
        ),
        migrations.AddField(
            model_name='historicalorderframe',
            name='quote',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='epic.Quote'),
        ),
        migrations.AddField(
            model_name='historicalorderitem',
            name='quotePart',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='epic.QuotePart'),
        ),
        migrations.AddField(
            model_name='orderframe',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Quote'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quotePart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.QuotePart'),
        ),
        migrations.AlterField(
            model_name='orderframe',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Supplier'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Supplier'),
        ),
    ]
