# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0018_orderpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpayment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='customerOrder',
        ),
        migrations.DeleteModel(
            name='OrderPayment',
        ),
    ]
