# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0020_auto_20171021_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='order_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomerorder',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomerorder',
            name='order_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
