# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0022_parttypeattribute_default_value_for_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttype',
            name='can_be_omitted',
            field=models.BooleanField(default=False, verbose_name='Can be omitted'),
        ),
        migrations.AddField(
            model_name='parttype',
            name='can_be_substituted',
            field=models.BooleanField(default=False, verbose_name='Can be substituted'),
        ),
    ]
