# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 15:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0023_auto_20171029_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.TextField(verbose_name='Colour')),
                ('colour_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('frameSize', models.TextField(verbose_name='Frame Size')),
            ],
        ),
        migrations.AddField(
            model_name='frame',
            name='colour',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='frame',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='framepart',
            name='not_applicable',
            field=models.BooleanField(default=False, verbose_name='Not Applicable'),
        ),
        migrations.AddField(
            model_name='parttype',
            name='customer_facing',
            field=models.BooleanField(default=False, verbose_name='Show Customer'),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='not_applicable',
            field=models.BooleanField(default=False, verbose_name='Not Applicable'),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='trade_in_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='historicalquote',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='historicalquote',
            name='keyed_sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='historicalquote',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='keyed_sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='quotepart',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='quotepart',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='date_placed',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Order Date'),
        ),
        migrations.AddField(
            model_name='quoteframe',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Quote'),
        ),
    ]
