# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0024_auto_20171105_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteframe',
            name='colour',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Colour'),
        ),
        migrations.AlterField(
            model_name='quoteframe',
            name='frameSize',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Frame Size'),
        ),
    ]
