# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0026_auto_20171119_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epic.Supplier'),
        ),
    ]
