# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0027_brand_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Frame')),
                ('partType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.PartType')),
            ],
        ),
        migrations.RemoveField(
            model_name='framepart',
            name='not_applicable',
        ),
        migrations.AlterUniqueTogether(
            name='frameexclusion',
            unique_together=set([('frame', 'partType')]),
        ),
    ]
