# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0028_auto_20171202_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotepart',
            name='not_applicable',
        ),
    ]
