# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0029_remove_quotepart_not_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderitem',
            name='stock_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stock_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='order_identifier',
            field=models.CharField(max_length=20, verbose_name='Order'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierorder',
            unique_together=set([('supplier', 'order_identifier')]),
        ),
    ]
