# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0030_auto_20171210_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteframe',
            name='quote',
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='cancelled_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='customer_required_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='final_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomerorder',
            name='cancelled_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomerorder',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomerorder',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcustomerorder',
            name='customer_required_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomerorder',
            name='final_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalquote',
            name='colour',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='historicalquote',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalquote',
            name='frame_size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalquote',
            name='issued_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalquote',
            name='quote_desc',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalquote',
            name='quote_status',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Quoted'), ('3', 'Archived'), ('4', 'Order Created')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalquote',
            name='quote_type',
            field=models.CharField(choices=[('B', 'Bike'), ('P', 'Parts')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='quote',
            name='colour',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='frame_size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='issued_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_desc',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_status',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Quoted'), ('3', 'Archived'), ('4', 'Order Created')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_type',
            field=models.CharField(choices=[('B', 'Bike'), ('P', 'Parts')], default='B', max_length=1),
        ),
        migrations.DeleteModel(
            name='QuoteFrame',
        ),
    ]
