# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0031_auto_20171227_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_option', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='customerorder',
            options={'ordering': ('-created_date', 'customer')},
        ),
        migrations.AddField(
            model_name='parttypeattribute',
            name='attribute_type',
            field=models.CharField(choices=[('1', 'Text'), ('2', 'Numeric'), ('3', 'Single - Radio'), ('4', 'Single - Dropdown'), ('5', 'Multiple - Checkbox'), ('6', 'Multiple - Dropdown')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalquote',
            name='quote_status',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Issued'), ('3', 'Archived'), ('4', 'Order Created')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_status',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Issued'), ('3', 'Archived'), ('4', 'Order Created')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='attributeoptions',
            name='part_type_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.PartTypeAttribute'),
        ),
    ]
