# Generated by Django 2.0.2 on 2018-03-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0034_auto_20180310_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotepartattribute',
            name='attribute_value',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
