# Generated by Django 2.0.2 on 2018-03-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0035_auto_20180317_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='sizes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
