# Generated by Django 2.0.3 on 2018-03-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0036_frame_sizes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='framepart',
            options={'ordering': ('pk',)},
        ),
    ]
