# Generated by Django 2.0.3 on 2018-03-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0037_auto_20180324_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(max_length=200),
        ),
    ]
