# Generated by Django 2.0.3 on 2018-04-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0038_auto_20180331_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='frame_cost_price',
        ),
    ]
