# Generated by Django 2.0.3 on 2018-04-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0039_remove_quote_frame_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotepart',
            name='is_incomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='is_not_standard_part',
            field=models.BooleanField(default=False),
        ),
    ]
