# Generated by Django 2.0.3 on 2018-04-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0041_auto_20180415_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotepart',
            options={},
        ),
        migrations.RenameField(
            model_name='quotepart',
            old_name='is_not_standard_part',
            new_name='replacement_part',
        ),
        migrations.RemoveField(
            model_name='parttypeattribute',
            name='default_value_for_quote',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='frame_part',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='line',
        ),
    ]
