# Generated by Django 2.0.3 on 2018-05-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0042_auto_20180429_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='upd_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AddField(
            model_name='customerphone',
            name='upd_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AddField(
            model_name='fitting',
            name='upd_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name', 'last_name', 'email'], name='epic_custom_first_n_8b4ffd_idx'),
        ),
    ]
