# Generated by Django 2.0.3 on 2018-05-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0043_auto_20180527_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotepart',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
