# Generated by Django 2.0.3 on 2018-06-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0044_auto_20180527_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributeoptions',
            options={'ordering': ('attribute_option',)},
        ),
        migrations.AlterField(
            model_name='brand',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerphone',
            name='telephone',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='parttypeattribute',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parttypeattribute',
            name='mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='frame',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='frameexclusion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='framepart',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='parttype',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='parttypeattribute',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='quotepartattribute',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supplierorder',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='attributeoptions',
            index=models.Index(fields=['part_type_attribute', 'attribute_option'], name='epic_attrib_part_ty_8d8194_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['brand_name'], name='epic_brand_brand_n_646d32_idx'),
        ),
        migrations.AddIndex(
            model_name='frame',
            index=models.Index(fields=['brand', 'frame_name', 'model'], name='epic_frame_brand_i_687d95_idx'),
        ),
        migrations.AddIndex(
            model_name='frameexclusion',
            index=models.Index(fields=['frame', 'partType'], name='epic_framee_frame_i_bf7a83_idx'),
        ),
        migrations.AddIndex(
            model_name='framepart',
            index=models.Index(fields=['frame', 'part'], name='epic_framep_frame_i_ae502a_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['partType', 'brand', 'part_name'], name='epic_part_partTyp_15352f_idx'),
        ),
        migrations.AddIndex(
            model_name='parttype',
            index=models.Index(fields=['includeInSection', 'shortName'], name='epic_partty_include_5e850d_idx'),
        ),
        migrations.AddIndex(
            model_name='parttypeattribute',
            index=models.Index(fields=['partType', 'attribute_name'], name='epic_partty_partTyp_87fce1_idx'),
        ),
        migrations.AddIndex(
            model_name='quotepartattribute',
            index=models.Index(fields=['quotePart', 'partTypeAttribute'], name='epic_quotep_quotePa_9c8c60_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierorder',
            index=models.Index(fields=['supplier', 'order_identifier'], name='epic_suppli_supplie_39c7b1_idx'),
        ),
    ]
