# Generated by Django 2.0.3 on 2018-06-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0045_auto_20180602_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderframe',
            name='customerOrder',
        ),
        migrations.RemoveField(
            model_name='orderframe',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='orderframe',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='orderframe',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='orderframe',
            name='supplierOrderItem',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='customerOrder',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='part',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quotePart',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='supplierOrderItem',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='customerOrder',
        ),
        migrations.RemoveField(
            model_name='supplierorder',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplierorderitem',
            name='supplierOrder',
        ),
        migrations.RemoveField(
            model_name='customernote',
            name='customerOrder',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='can_be_ordered',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='customerOrder',
        ),
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
        migrations.DeleteModel(
            name='OrderFrame',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='OrderPayment',
        ),
        migrations.DeleteModel(
            name='SupplierOrder',
        ),
        migrations.DeleteModel(
            name='SupplierOrderItem',
        ),
    ]
