# Generated by Django 2.0.3 on 2018-06-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0046_auto_20180608_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='cost_price',
        ),
        migrations.AddField(
            model_name='quote',
            name='upd_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='colour',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='model',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='frame',
            name='sizes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
