# Generated by Django 2.0.3 on 2018-06-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0047_auto_20180621_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frame',
            name='archived_date',
            field=models.DateTimeField(null=True),
        ),
    ]
