# Generated by Django 2.0.3 on 2018-06-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0048_auto_20180622_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='archived_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
