# Generated by Django 2.0.3 on 2018-11-03 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0049_auto_20180629_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parttype',
            name='description',
        ),
        migrations.AddField(
            model_name='attributeoptions',
            name='placing',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attributeoptions',
            name='part_type_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='epic.PartTypeAttribute'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='epic.Customer'),
        ),
        migrations.AlterField(
            model_name='customernote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customernote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='epic.Customer'),
        ),
        migrations.AlterField(
            model_name='customernote',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='epic.Quote'),
        ),
        migrations.AlterField(
            model_name='customerphone',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='epic.Customer'),
        ),
        migrations.AlterField(
            model_name='fitting',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fittings', to='epic.Customer'),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='includeInSection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partTypes', to='epic.PartSection'),
        ),
        migrations.AlterField(
            model_name='parttypeattribute',
            name='partType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='epic.PartType'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='epic.Customer'),
        ),
    ]
