# Generated by Django 2.0.3 on 2018-11-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0051_auto_20181124_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='preferred_supplier',
            field=models.BooleanField(default=True, verbose_name='Preferred'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.CharField(blank=True, max_length=200, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
