# Generated by Django 2.0.3 on 2018-12-01 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0052_auto_20181125_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('colours', models.CharField(blank=True, max_length=400, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('sizes', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BikePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_name', models.CharField(max_length=100, unique=True, verbose_name='Supplier')),
                ('fitted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartTradeIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_in_value', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartTypeSynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortName', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=30)),
                ('fitted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('rrp', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('trade_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('club_discount', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='framepart',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='framepart',
            name='part',
        ),
        migrations.AlterModelOptions(
            name='frame',
            options={'ordering': ('brand', 'frame_name')},
        ),
        migrations.RemoveIndex(
            model_name='frame',
            name='epic_frame_brand_i_687d95_idx',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='description',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='model',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='sizes',
        ),
        migrations.AddField(
            model_name='part',
            name='stocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='frame',
            index=models.Index(fields=['brand', 'frame_name'], name='epic_frame_brand_i_fae71e_idx'),
        ),
        migrations.DeleteModel(
            name='FramePart',
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Part'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Supplier'),
        ),
        migrations.AddField(
            model_name='parttypesynonym',
            name='partType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='epic.PartType'),
        ),
        migrations.AddField(
            model_name='parttradein',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Part'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='products',
            field=models.ManyToManyField(blank=True, to='epic.SupplierProduct'),
        ),
        migrations.AddField(
            model_name='bikepart',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Bike'),
        ),
        migrations.AddField(
            model_name='bikepart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Part'),
        ),
        migrations.AddField(
            model_name='bike',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Frame'),
        ),
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['supplier', 'part'], name='epic_suppli_supplie_040de4_idx'),
        ),
        migrations.AddIndex(
            model_name='bikepart',
            index=models.Index(fields=['bike', 'part'], name='epic_bikepa_bike_id_03189d_idx'),
        ),
    ]
