# Generated by Django 2.0.3 on 2018-12-14 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0053_auto_20181201_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parttradein',
            name='part',
        ),
        migrations.AddField(
            model_name='brand',
            name='bike_brand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='standard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='trade_in_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='epic.Frame'),
        ),
        migrations.DeleteModel(
            name='PartTradeIn',
        ),
    ]
