# Generated by Django 2.0.3 on 2018-12-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0055_auto_20181223_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='sell_price',
            new_name='club_price',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='club_discount',
        ),
        migrations.AddField(
            model_name='bike',
            name='epic_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='rrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='club_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='bundle_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
