# Generated by Django 2.0.3 on 2018-12-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0056_auto_20181228_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='check_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
