# Generated by Django 2.0.3 on 2019-01-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0057_supplierproduct_check_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='country',
            field=models.CharField(default='GB', max_length=2),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
