# Generated by Django 2.0.3 on 2019-03-22 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0061_auto_20190119_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='can_be_issued',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='is_incomplete',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerphone',
            name='preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bike',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epic.Frame'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_desc',
            field=models.CharField(max_length=120),
        ),
    ]
