# Generated by Django 2.0.3 on 2019-04-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0062_auto_20190322_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotepart',
            old_name='club_price',
            new_name='quote_price',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='club_price',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='epic_price',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='rrp',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='epic_price',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='rrp',
        ),
        migrations.RemoveField(
            model_name='quotepart',
            name='trade_in_price',
        ),
    ]
