# Generated by Django 2.0.3 on 2019-04-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0063_auto_20190404_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotepartattribute',
            name='partTypeAttribute',
        ),
        migrations.RemoveField(
            model_name='quotepartattribute',
            name='quotePart',
        ),
        migrations.AddField(
            model_name='quotepart',
            name='additional_data',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='QuotePartAttribute',
        ),
    ]
