# Generated by Django 2.0.3 on 2019-04-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0064_auto_20190405_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotepart',
            old_name='replacement_part',
            new_name='not_required',
        ),
    ]
