# Generated by Django 2.0.3 on 2019-04-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0065_auto_20190408_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotepart',
            old_name='quote_price',
            new_name='part_price',
        ),
        migrations.AddField(
            model_name='quotepart',
            name='trade_in_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
