# Generated by Django 2.0.3 on 2019-04-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0067_auto_20190413_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='club_member',
            field=models.BooleanField(default=False),
        ),
    ]
