# Generated by Django 2.0.3 on 2019-04-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0069_auto_20190416_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customernote',
            options={'ordering': ('-created_date', 'created_by')},
        ),
        migrations.AddField(
            model_name='quote',
            name='calculated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
