# Generated by Django 2.0.3 on 2019-04-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic', '0070_auto_20190425_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='bike_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
